package resto;

/*
 * RestoF.java
 *
 * Created on June 16, 2007, 9:43 PM
 */
/**
 *
 * @author Saut_private
 */
import aksi.aksi_resto;
import java.awt.*;
import java.awt.event.*;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.swing.*;
import javax.swing.ButtonModel;
import javax.swing.border.*;
import javax.swing.table.*;
import javax.print.event.PrintEvent.*;
import java.awt.Color;
import javax.swing.JLabel;
import javax.swing.JDesktopPane;
import java.awt.ItemSelectable;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.text.EditorKit;
import javax.swing.text.html.HTMLEditorKit;
import koneksi.koneksi;
import org.jdesktop.layout.GroupLayout.*;

public class RestoF extends javax.swing.JFrame {

    Connection con;
    Statement st;
    ResultSet ress;
    JTextPane jp1 = new JTextPane();

    String harga1;

    /**
     * Creates new form RestoF
     */
    public RestoF() {
        setTitle("101 Cafe Rolls");
        initComponents();
        add();
//        tanggal_1();

    }

//    public void tanggal_1() {
//        java.util.Date skrg = new java.util.Date();
//        java.text.SimpleDateFormat kal = new java.text.SimpleDateFormat("dd-MM-yyyy");
//        tanggal.setText(kal.format(skrg));
//        tanggal.disable();
//    }

//    void harga_satu() {
//        harga1 = TEXTharga.getText();
////        System.out.println(harga1);
//    }
    void simpan() {
//        con = new koneksi.koneksi().getConnection();
        try {
//                    Connection con = new koneksi().getConnection();
            con = new koneksi().getConnection();
            String sql = "insert into pemesanan values('" + 0 + "','" + atas_nm.getText() + "','" + TEXTjml.getText() + "','" + tanggal.getText() + "','" + TEXTharga.getText() + "','" + nama.getText() + "')";
            Statement st = con.createStatement();
            st.executeUpdate(sql);
            JOptionPane.showMessageDialog(null, "Data BERHASIL biologi", "Informasi", JOptionPane.INFORMATION_MESSAGE);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Data GAGAL tersimpan", "Informasi", JOptionPane.INFORMATION_MESSAGE);
            System.out.println(e);
        }
    }

    ;
    

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        TEXThargaKembalian = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        TEXTharga = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        TEXTjml = new javax.swing.JTextField();
        Tambah = new javax.swing.JButton();
        Resetbtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabel = new javax.swing.JTable();
        Bayarbtn = new javax.swing.JButton();
        Hapusbtn = new javax.swing.JButton();
        cal1btn = new javax.swing.JButton();
        cal2btn = new javax.swing.JButton();
        cal3btn = new javax.swing.JButton();
        cal4btn = new javax.swing.JButton();
        cal5btn = new javax.swing.JButton();
        cal6btn = new javax.swing.JButton();
        cal7btn = new javax.swing.JButton();
        cal8btn = new javax.swing.JButton();
        cal9btn = new javax.swing.JButton();
        cal0btn = new javax.swing.JButton();
        TEXTbayar = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        nama = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        satuan = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        TEXTkembalian = new javax.swing.JTextField();
        TEXTid = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        Add = new javax.swing.JCheckBox();
        Bayar = new javax.swing.JCheckBox();
        jButton6 = new javax.swing.JButton();
        atas_nm = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        Makanan1btn = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        Makanan1btn2 = new javax.swing.JButton();
        Makanan1btn3 = new javax.swing.JButton();
        Makanan1btn4 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        Makanan1btn5 = new javax.swing.JButton();
        Makanan1btn6 = new javax.swing.JButton();
        Makanan1btn7 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        tanggal = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("RP");

        TEXTharga.setEditable(false);
        TEXTharga.setBackground(new java.awt.Color(204, 204, 204));
        TEXTharga.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        TEXTharga.setText("0");
        TEXTharga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TEXThargaActionPerformed(evt);
                TEXThargaKembalian(evt);
            }
        });

        jLabel2.setText("Jumlah");

        TEXTjml.setColumns(2);
        TEXTjml.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        TEXTjml.setText("1");
        TEXTjml.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TEXTjmlActionPerformed(evt);
            }
        });

        Tambah.setText("Add");
        Tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Tambahpsn(evt);
            }
        });

        Resetbtn.setText("Reset");
        Resetbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Reset(evt);
            }
        });

        Tabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Paket", "Jumlah", "Harga", "Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(Tabel);

        Bayarbtn.setText("Bayar");
        Bayarbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bayar(evt);
            }
        });

        Hapusbtn.setText("Hapus");
        Hapusbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HapusMknMnm(evt);
            }
        });

        cal1btn.setText("1");
        cal1btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cal1(evt);
            }
        });

        cal2btn.setText("2");
        cal2btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cal2(evt);
            }
        });

        cal3btn.setText("3");
        cal3btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cal3(evt);
            }
        });

        cal4btn.setText("4");
        cal4btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cal4(evt);
            }
        });

        cal5btn.setText("5");
        cal5btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cal5(evt);
            }
        });

        cal6btn.setText("6");
        cal6btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cal6(evt);
            }
        });

        cal7btn.setText("7");
        cal7btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cal7(evt);
            }
        });

        cal8btn.setText("8");
        cal8btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cal8(evt);
            }
        });

        cal9btn.setText("9");
        cal9btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cal9(evt);
            }
        });

        cal0btn.setText("0");
        cal0btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cal0(evt);
            }
        });

        TEXTbayar.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        TEXTbayar.setText("0");
        TEXTbayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TEXTbayarActionPerformed(evt);
            }
        });

        jLabel3.setText("Makanan dan Minum");

        nama.setEditable(false);

        jLabel5.setText("Harga @");

        satuan.setEditable(false);

        jLabel4.setText("Kembalian");

        TEXTkembalian.setEditable(false);
        TEXTkembalian.setBackground(new java.awt.Color(204, 204, 204));
        TEXTkembalian.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        TEXTkembalian.setText("0");
        TEXTkembalian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TEXTkembalianActionPerformed(evt);
            }
        });

        TEXTid.setEditable(false);
        TEXTid.setBackground(new java.awt.Color(204, 204, 204));
        TEXTid.setText("0");
        TEXTid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TEXTidActionPerformed(evt);
            }
        });

        jLabel8.setText("ID number");

        Add.setSelected(true);
        Add.setText("Add");
        Add.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        Add.setMargin(new java.awt.Insets(0, 0, 0, 0));
        Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddActionPerformed(evt);
            }
        });

        Bayar.setText("Pay");
        Bayar.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        Bayar.setMargin(new java.awt.Insets(0, 0, 0, 0));
        Bayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BayarActionPerformed(evt);
            }
        });

        jButton6.setText("Simpan");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jLabel11.setText("Atas Nama");

        org.jdesktop.layout.GroupLayout TEXThargaKembalianLayout = new org.jdesktop.layout.GroupLayout(TEXThargaKembalian);
        TEXThargaKembalian.setLayout(TEXThargaKembalianLayout);
        TEXThargaKembalianLayout.setHorizontalGroup(
            TEXThargaKembalianLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(TEXThargaKembalianLayout.createSequentialGroup()
                .add(TEXThargaKembalianLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(TEXThargaKembalianLayout.createSequentialGroup()
                        .addContainerGap()
                        .add(TEXThargaKembalianLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 28, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jLabel2))
                        .add(12, 12, 12)
                        .add(TEXThargaKembalianLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 415, Short.MAX_VALUE)
                            .add(TEXThargaKembalianLayout.createSequentialGroup()
                                .add(TEXTharga, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 139, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(0, 0, Short.MAX_VALUE))
                            .add(TEXThargaKembalianLayout.createSequentialGroup()
                                .add(TEXThargaKembalianLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(jLabel3)
                                    .add(jLabel5)
                                    .add(TEXTjml, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(jLabel11))
                                .add(39, 39, 39)
                                .add(TEXThargaKembalianLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(atas_nm)
                                    .add(nama, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
                                    .add(satuan, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
                                    .add(TEXThargaKembalianLayout.createSequentialGroup()
                                        .add(13, 13, 13)
                                        .add(TEXThargaKembalianLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                                            .add(TEXThargaKembalianLayout.createSequentialGroup()
                                                .add(jLabel4)
                                                .add(2, 2, 2))
                                            .add(jLabel8))
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                        .add(TEXThargaKembalianLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                            .add(TEXTkembalian, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 149, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                            .add(TEXTid, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 82, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                        .add(0, 0, Short.MAX_VALUE))))))
                    .add(TEXThargaKembalianLayout.createSequentialGroup()
                        .add(78, 78, 78)
                        .add(TEXThargaKembalianLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, cal0btn, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .add(TEXThargaKembalianLayout.createSequentialGroup()
                                .add(TEXThargaKembalianLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                                    .add(cal7btn)
                                    .add(cal1btn)
                                    .add(cal4btn))
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(TEXThargaKembalianLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                                    .add(TEXThargaKembalianLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                        .add(cal8btn)
                                        .add(cal5btn))
                                    .add(cal2btn))
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(TEXThargaKembalianLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(cal9btn)
                                    .add(cal3btn)
                                    .add(cal6btn))))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 61, Short.MAX_VALUE)
                        .add(TEXThargaKembalianLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(TEXThargaKembalianLayout.createSequentialGroup()
                                .add(Bayarbtn)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .add(TEXTbayar, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 116, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                            .add(Hapusbtn, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .add(Bayar)
                            .add(Add)
                            .add(TEXThargaKembalianLayout.createSequentialGroup()
                                .add(Tambah, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 62, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(Resetbtn)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jButton6)))))
                .addContainerGap())
        );
        TEXThargaKembalianLayout.setVerticalGroup(
            TEXThargaKembalianLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(TEXThargaKembalianLayout.createSequentialGroup()
                .addContainerGap()
                .add(TEXThargaKembalianLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 29, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(TEXTharga, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel4)
                    .add(TEXTkembalian, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(TEXThargaKembalianLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel2)
                    .add(TEXTid, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(TEXTjml, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel8))
                .add(10, 10, 10)
                .add(TEXThargaKembalianLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(atas_nm, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel11))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(TEXThargaKembalianLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel3)
                    .add(nama, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(TEXThargaKembalianLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel5)
                    .add(satuan, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(22, 22, 22)
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 223, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(16, 16, 16)
                .add(TEXThargaKembalianLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(TEXThargaKembalianLayout.createSequentialGroup()
                        .add(TEXThargaKembalianLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(cal1btn)
                            .add(cal3btn)
                            .add(cal2btn))
                        .add(18, 18, 18)
                        .add(TEXThargaKembalianLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(cal4btn)
                            .add(cal5btn)
                            .add(cal6btn))
                        .add(16, 16, 16))
                    .add(TEXThargaKembalianLayout.createSequentialGroup()
                        .add(TEXThargaKembalianLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(Bayarbtn)
                            .add(TEXTbayar, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(Hapusbtn)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(Add)
                        .add(6, 6, 6)))
                .add(TEXThargaKembalianLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(TEXThargaKembalianLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                        .add(cal9btn)
                        .add(cal8btn)
                        .add(cal7btn))
                    .add(Bayar))
                .add(18, 18, 18)
                .add(TEXThargaKembalianLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(cal0btn)
                    .add(Resetbtn)
                    .add(Tambah)
                    .add(jButton6))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Makanan1btn.setBackground(new java.awt.Color(255, 255, 255));
        Makanan1btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/a.jpg"))); // NOI18N
        Makanan1btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Makanan1btn(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("MINUMAN");

        Makanan1btn2.setBackground(new java.awt.Color(255, 255, 255));
        Makanan1btn2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/extra jos.gif"))); // NOI18N
        Makanan1btn2.setText("JOSUA");
        Makanan1btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Makanan1btn2(evt);
            }
        });

        Makanan1btn3.setBackground(new java.awt.Color(255, 255, 255));
        Makanan1btn3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/java-icon.gif"))); // NOI18N
        Makanan1btn3.setText("KOPI IJO");
        Makanan1btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Makanan1btn3(evt);
            }
        });

        Makanan1btn4.setBackground(new java.awt.Color(255, 255, 255));
        Makanan1btn4.setText("SUSU");
        Makanan1btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Makanan1btn4(evt);
            }
        });

        jLabel12.setText("Kopi Ireng");

        jLabel13.setText("Kopi Ijo");

        jLabel14.setText("Josua");

        jLabel15.setText("Susu");

        org.jdesktop.layout.GroupLayout jPanel2Layout = new org.jdesktop.layout.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel2Layout.createSequentialGroup()
                        .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jPanel2Layout.createSequentialGroup()
                                .add(jLabel6)
                                .add(12, 12, 12))
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel2Layout.createSequentialGroup()
                                .add(Makanan1btn, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 92, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)))
                        .add(Makanan1btn3, 0, 1, Short.MAX_VALUE)
                        .add(18, 18, 18))
                    .add(jPanel2Layout.createSequentialGroup()
                        .add(jLabel12, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 92, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(jLabel13)
                        .add(74, 74, 74)))
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(Makanan1btn2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 100, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel14))
                .add(18, 18, 18)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel2Layout.createSequentialGroup()
                        .add(jLabel15)
                        .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .add(jPanel2Layout.createSequentialGroup()
                        .add(Makanan1btn4, 0, 94, Short.MAX_VALUE)
                        .add(385, 385, 385))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createSequentialGroup()
                .add(36, 36, 36)
                .add(jLabel6)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(Makanan1btn2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 70, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(Makanan1btn3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 70, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(Makanan1btn4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 70, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(Makanan1btn, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 70, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(18, 18, 18)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel12)
                    .add(jLabel13)
                    .add(jLabel14)
                    .add(jLabel15))
                .addContainerGap())
        );

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("MAKAN");

        Makanan1btn5.setBackground(new java.awt.Color(255, 255, 255));
        Makanan1btn5.setText("K.GORENG");
        Makanan1btn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Makanan1btn5(evt);
            }
        });

        Makanan1btn6.setBackground(new java.awt.Color(255, 255, 255));
        Makanan1btn6.setText("INDOMI");
        Makanan1btn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Makanan1btn6(evt);
            }
        });

        Makanan1btn7.setBackground(new java.awt.Color(255, 255, 255));
        Makanan1btn7.setText("RT.MARIAM");
        Makanan1btn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Makanan1btn7(evt);
            }
        });

        jLabel16.setText("Indomie");

        jLabel17.setText("Roti Maryam");

        jLabel18.setText("Kentang Goreng");

        org.jdesktop.layout.GroupLayout jPanel3Layout = new org.jdesktop.layout.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel3Layout.createSequentialGroup()
                .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .add(jLabel7))
                    .add(jPanel3Layout.createSequentialGroup()
                        .add(23, 23, 23)
                        .add(jLabel16)
                        .add(76, 76, 76)
                        .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(Makanan1btn7, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 92, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jLabel17))
                        .add(28, 28, 28)
                        .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabel18)
                            .add(Makanan1btn5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 92, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                .add(jPanel3Layout.createSequentialGroup()
                    .add(20, 20, 20)
                    .add(Makanan1btn6, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 92, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(580, Short.MAX_VALUE)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel7)
                .add(18, 18, 18)
                .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(Makanan1btn5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 70, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(Makanan1btn7, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 70, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel16)
                    .add(jLabel17)
                    .add(jLabel18))
                .addContainerGap(95, Short.MAX_VALUE))
            .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                .add(jPanel3Layout.createSequentialGroup()
                    .add(42, 42, 42)
                    .add(Makanan1btn6, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 70, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(122, Short.MAX_VALUE)))
        );

        jLabel9.setText("Jl. Jagoanngoding.com");

        jLabel10.setText("Malang Santai");

        org.jdesktop.layout.GroupLayout jPanel4Layout = new org.jdesktop.layout.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel4Layout.createSequentialGroup()
                .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel4Layout.createSequentialGroup()
                        .add(24, 24, 24)
                        .add(jLabel10))
                    .add(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .add(jLabel9, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 271, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel4Layout.createSequentialGroup()
                .add(23, 23, 23)
                .add(jLabel9, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 24, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jLabel10)
                .addContainerGap(69, Short.MAX_VALUE))
        );

        tanggal.setText("jTextField1");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .add(TEXThargaKembalian, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(30, 30, 30)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                    .add(jPanel4, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jPanel3, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(jPanel2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(tanggal, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 157, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(359, 359, 359))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(tanggal, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, TEXThargaKembalian, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, layout.createSequentialGroup()
                        .add(jPanel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(1, 1, 1)
                        .add(jPanel3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(jPanel4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Makanan1btn(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Makanan1btn
// TODO add your handling codse here:
//        try {
//            con = new koneksi().getConnection();
//            st = (com.mysql.jdbc.Statement) con.createStatement();
//            String sql = "SELECT * FROM `menu` WHERE id_menu='" + "1" + "'";
//            st = con.createStatement();
//            ResultSet res = st.executeQuery(sql);
//
//            while (res.next()) {
////                getmenu_utama().getkombo().addItem(res.getString(1));
//                nama.setText(res.getString(2));
//                satuan.setText(res.getString(3));
//            }
//        } catch (Exception e) {
//        }

    }//GEN-LAST:event_Makanan1btn

    private void BayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BayarActionPerformed
// TODO add your handling code here:
        buttonGroup2.add(Bayar);
    }//GEN-LAST:event_BayarActionPerformed

    private void AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddActionPerformed
// TODO add your handling code here:
        buttonGroup2.add(Add);
    }//GEN-LAST:event_AddActionPerformed

    private void TEXTbayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TEXTbayarActionPerformed
// TODO add your handling code here:
    }//GEN-LAST:event_TEXTbayarActionPerformed

    private void TEXTidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TEXTidActionPerformed
// TODO add your handling code here:
    }//GEN-LAST:event_TEXTidActionPerformed

    private void TEXThargaKembalian(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TEXThargaKembalian
// TODO add your handling code here:
    }//GEN-LAST:event_TEXThargaKembalian

    private void Bayar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bayar
// TODO add your handling code here:
        try {
            int a = Integer.parseInt(TEXTbayar.getText());
            int b = Integer.parseInt(TEXTharga.getText());
            if ((Tabel.getValueAt(0, 0) != null) && (a >= b)) {
                int c = a - b;
                String baru4 = Integer.toString(c);
                TEXTkembalian.setText(baru4);
                Calendar d = new GregorianCalendar();
                String s = String.format("%1$te%1$tb%1$ty", d);
                try {
                    PrintWriter out = new PrintWriter(new FileWriter("d:\\transaksi" + s.toString() + ".txt", true));
                    writeData(out);
                    out.close();
                } catch (IOException ex) {
                    ex.printStackTrace();
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Salah Input", "RestoKu", JOptionPane.ERROR_MESSAGE);

        }
        int a = Integer.parseInt(TEXTbayar.getText());
        int b = Integer.parseInt(TEXTharga.getText());
        if ((Tabel.getValueAt(0, 0) != null) && (a < b)) {
            TEXTkembalian.setText("UANG TIDAK CUKUP");
            JOptionPane.showMessageDialog(null, "Uang tidak cukup", "RestoKu", JOptionPane.ERROR_MESSAGE);
        }

        if ((Tabel.getValueAt(0, 0) != null) && (a >= b)) {
            int id = Integer.parseInt(TEXTid.getText());
            int idcount = id + 1;
            String idcount2 = Integer.toString(idcount);

            TEXTid.setText(idcount2);
        }
        if ((Tabel.getValueAt(0, 0) != null) && (a < b)) {
            int id = Integer.parseInt(TEXTid.getText());
            int idcount = id;
            String idcount2 = Integer.toString(idcount);

            TEXTid.setText(idcount2);
        }
        if (TEXTbayar.getText() == " ") {
            TEXTkembalian.setText("salah");
        }
    }//GEN-LAST:event_Bayar

    private void HapusMknMnm(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HapusMknMnm
// TODO add your handling code here:
        int a = -1;
        a = Tabel.getSelectedRow();
        int b = i - 1;
        if ((i > 0) && (a >= 0) && (a < i)) {
            int p = Integer.parseInt((String) Tabel.getValueAt(a, 2));
            for (; a < b; a++) {
                Tabel.setValueAt(Tabel.getValueAt(a + 1, 0), a, 0);
                Tabel.setValueAt(Tabel.getValueAt(a + 1, 1), a, 1);
                Tabel.setValueAt(Tabel.getValueAt(a + 1, 2), a, 2);
                Tabel.setValueAt(Tabel.getValueAt(a + 1, 3), a, 3);
            }
            Tabel.setValueAt(null, b, 0);
            Tabel.setValueAt(null, b, 1);
            Tabel.setValueAt(null, b, 2);
            Tabel.setValueAt(null, b, 3);
            i--;
            j = j - p;
            String baru6 = Integer.toString(j);
            TEXTharga.setText(baru6);
        }
    }//GEN-LAST:event_HapusMknMnm

    private void Reset(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Reset
// TODO add your handling code here:
//        if (TEXTharga.getText() != "0") {
//            nama.setText("");
//            TEXTbayar.setText("0");
//            j = 0;
//            satuan.setText("");
//            TEXTjml.setText("0");
//            TEXTharga.setText("0");
//            temp = "";
//            harga = "";
//            satuan.setText("");
//            TEXTkembalian.setText("0");
//            for (; i >= 0; i--) {
//                Tabel.setValueAt(null, i, 0);
//                Tabel.setValueAt(null, i, 1);
//                Tabel.setValueAt(null, i, 2);
//                Tabel.setValueAt(null, i, 3);
//            }
//            i = 0;
//        }
    }//GEN-LAST:event_Reset

    private void Tambahpsn(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Tambahpsn
// TODO add your handling code here:
//        try {
//            String a, b, c, d;//a=nama , b=jumlah , c=harga , d=total
//            int p, r, u, s, t;
//            r = Integer.parseInt(TEXTjml.getText());
//            u = Integer.parseInt(satuan.getText());
//
//            s = r * u;
//
//            d = Integer.toString(s);
//
//            if (nama.getText() != "") {
//                a = nama.getText();
//                b = TEXTjml.getText();
//                c = satuan.getText();
//                Tabel.setValueAt(a, i, 0);
//                Tabel.setValueAt(b, i, 1);
//                Tabel.setValueAt(c, i, 2);
//                Tabel.setValueAt(d, i, 3);
//                i++;
//                p = Integer.parseInt(d);
//                j = j + p;
//                String baru5 = Integer.toString(j);
//                TEXTharga.setText(baru5);
//            }
//        } catch (Exception e) {
//            JOptionPane.showMessageDialog(null, "Input Salah", "RestoKu", JOptionPane.ERROR_MESSAGE);
//        }
    }//GEN-LAST:event_Tambahpsn

    private void TEXThargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TEXThargaActionPerformed
// TODO add your handling code here:

    }//GEN-LAST:event_TEXThargaActionPerformed

    private void TEXTjmlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TEXTjmlActionPerformed
// TODO add your handling code here:
    }//GEN-LAST:event_TEXTjmlActionPerformed

    private void cal0(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cal0
// TODO add your handling code here:
        if (Bayar.isSelected()) {
            TEXTbayar.setText(harga + "0");
            harga = harga + "0";
        }
        if (Add.isSelected()) {
            TEXTjml.setText(temp = temp + 0);
        }
    }//GEN-LAST:event_cal0

    private void cal9(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cal9
// TODO add your handling code here:
        if (Bayar.isSelected()) {
            TEXTbayar.setText(harga + "9");
            harga = harga + "9";
        }
        if (Add.isSelected()) {
            TEXTjml.setText(temp = temp + 9);
        }
    }//GEN-LAST:event_cal9

    private void cal8(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cal8
// TODO add your handling code here:
        if (Bayar.isSelected()) {
            TEXTbayar.setText(harga + "8");
            harga = harga + "8";
        }
        if (Add.isSelected()) {
            TEXTjml.setText(temp = temp + 8);
        }

    }//GEN-LAST:event_cal8

    private void cal7(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cal7
// TODO add your handling code here:
        if (Bayar.isSelected()) {
            TEXTbayar.setText(harga + "7");
            harga = harga + "7";
        }
        if (Add.isSelected()) {
            TEXTjml.setText(temp = temp + 7);
        }
    }//GEN-LAST:event_cal7

    private void cal6(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cal6
// TODO add your handling code here:
        if (Bayar.isSelected()) {
            TEXTbayar.setText(harga + "6");
            harga = harga + "6";
        }
        if (Add.isSelected()) {
            TEXTjml.setText(temp = temp + 6);
        }
    }//GEN-LAST:event_cal6

    private void cal5(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cal5
// TODO add your handling code here:
        if (Bayar.isSelected()) {
            TEXTbayar.setText(harga + "5");
            harga = harga + "5";
        }
        if (Add.isSelected()) {
            TEXTjml.setText(temp = temp + 5);
        }
    }//GEN-LAST:event_cal5

    private void cal4(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cal4
// TODO add your handling code here:
        if (Bayar.isSelected()) {
            TEXTbayar.setText(harga + "4");
            harga = harga + "4";
        }
        if (Add.isSelected()) {
            TEXTjml.setText(temp = temp + 4);
        }
    }//GEN-LAST:event_cal4

    private void cal3(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cal3
// TODO add your handling code here:
        if (Bayar.isSelected()) {
            TEXTbayar.setText(harga + "3");
            harga = harga + "3";
        }
        if (Add.isSelected()) {
            TEXTjml.setText(temp = temp + 3);
        }
    }//GEN-LAST:event_cal3

    private void cal2(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cal2
// TODO add your handling code here:
        if (Bayar.isSelected()) {
            TEXTbayar.setText(harga + "2");
            harga = harga + "2";
        }
        if (Add.isSelected()) {
            TEXTjml.setText(temp = temp + 2);
        }
    }//GEN-LAST:event_cal2

    private void cal1(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cal1
// TODO add your handling code here:

        if (Bayar.isSelected()) {
            TEXTbayar.setText(harga + "1");
            harga = harga + "1";
        }
        if (Add.isSelected()) {
            TEXTjml.setText(temp = temp + 1);
        }

    }//GEN-LAST:event_cal1

private void TEXTkembalianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TEXTkembalianActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_TEXTkembalianActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
//        simpan();
//        try {
//            Tabel.print();
//        } catch (Exception e) {
//        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void Makanan1btn2(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Makanan1btn2
        // TODO add your handling code here:
    }//GEN-LAST:event_Makanan1btn2

    private void Makanan1btn3(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Makanan1btn3
        // TODO add your handling code here:
    }//GEN-LAST:event_Makanan1btn3

    private void Makanan1btn4(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Makanan1btn4
        // TODO add your handling code here:
    }//GEN-LAST:event_Makanan1btn4

    private void Makanan1btn5(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Makanan1btn5
        // TODO add your handling code here:
    }//GEN-LAST:event_Makanan1btn5

    private void Makanan1btn6(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Makanan1btn6
        // TODO add your handling code here:
    }//GEN-LAST:event_Makanan1btn6

    private void Makanan1btn7(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Makanan1btn7
        // TODO add your handling code here:
    }//GEN-LAST:event_Makanan1btn7
    private void writeData(PrintWriter out) throws IOException {
        out.print("transaksi ke : " + (k + 1));
        out.println("");
        out.println("Pesanan     Jumlah     Harga     Total");
        for (int e = 0; e < i; e++) {
            out.println("");
            out.print(Tabel.getValueAt(e, 0) + "     ");
            out.print(Tabel.getValueAt(e, 1) + "     ");
            out.print(Tabel.getValueAt(e, 2) + "     ");
            out.print(Tabel.getValueAt(e, 3));
        }
        out.println("");
        out.println("");
        out.println("harga total = Rp" + TEXTharga.getText());
        out.println("pembayaran  = Rp" + TEXTbayar.getText());
        out.println("kembalian   = Rp" + TEXTkembalian.getText());
        out.println("");
        out.println("");
        out.println("");
        out.println("");
        k++;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {

                new RestoF().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox Add;
    private javax.swing.JCheckBox Bayar;
    private javax.swing.JButton Bayarbtn;
    private javax.swing.JButton Hapusbtn;
    private javax.swing.JButton Makanan1btn;
    private javax.swing.JButton Makanan1btn2;
    private javax.swing.JButton Makanan1btn3;
    private javax.swing.JButton Makanan1btn4;
    private javax.swing.JButton Makanan1btn5;
    private javax.swing.JButton Makanan1btn6;
    private javax.swing.JButton Makanan1btn7;
    private javax.swing.JButton Resetbtn;
    private javax.swing.JTextField TEXTbayar;
    private javax.swing.JTextField TEXTharga;
    private javax.swing.JPanel TEXThargaKembalian;
    private javax.swing.JTextField TEXTid;
    private javax.swing.JTextField TEXTjml;
    private javax.swing.JTextField TEXTkembalian;
    private javax.swing.JTable Tabel;
    private javax.swing.JButton Tambah;
    private javax.swing.JTextField atas_nm;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton cal0btn;
    private javax.swing.JButton cal1btn;
    private javax.swing.JButton cal2btn;
    private javax.swing.JButton cal3btn;
    private javax.swing.JButton cal4btn;
    private javax.swing.JButton cal5btn;
    private javax.swing.JButton cal6btn;
    private javax.swing.JButton cal7btn;
    private javax.swing.JButton cal8btn;
    private javax.swing.JButton cal9btn;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nama;
    private javax.swing.JTextField satuan;
    private javax.swing.JTextField tanggal;
    // End of variables declaration//GEN-END:variables
    int total = 0;
    int i, j, k;
    String baru;
    String harga = "";
    String temp = "";

    void add() {
        aksi_resto aksi = new aksi_resto(this);
        jButton6.addMouseListener(aksi.simpan);
        Tambah.addMouseListener(aksi.add);
        Resetbtn.addMouseListener(aksi.bersih);
        Makanan1btn.addMouseListener(aksi.kopi_ireng);
        Makanan1btn3.addMouseListener(aksi.kopi_ijo);
        Makanan1btn2.addMouseListener(aksi.josua);
        Makanan1btn4.addMouseListener(aksi.susu);
        Makanan1btn6.addMouseListener(aksi.Indomi);
        Makanan1btn7.addMouseListener(aksi.mariam);
        Makanan1btn5.addMouseListener(aksi.goreng);
    }

    public JTextField getatas_nama() {
        return atas_nm;
    }

    public void setatas_nama(JTextField atas_nama) {
        this.atas_nm = atas_nama;
    }
//    TEXTjml

    public JTextField getTEXTjml() {
        return TEXTjml;
    }

    public void setatTEXTjml(JTextField TEXTjml) {
        this.TEXTjml = TEXTjml;
    }
//   tanggal

    public JTextField gettanggal() {
        return tanggal;
    }

    public void setattanggal(JTextField tanggal) {
        this.tanggal = tanggal;
    }

    // TEXTharga
    public JTextField getTEXTharga() {
        return TEXTharga;
    }

    public void setTEXTharga(JTextField TEXTharga) {
        this.TEXTharga = TEXTharga;
    }

    // nama
    public JTextField getnama() {
        return nama;
    }

    public void setnama(JTextField nama) {
        this.nama = nama;
    }

    // Jtabel add Tabel
    public JTable getTabel() {
        return Tabel;
    }

    public void setTabel(JTable Tabel) {
        this.Tabel = Tabel;
    }

    // satua
    public JTextField getsatuan() {
        return satuan;
    }

    public void setsatuan(JTextField satuan) {
        this.satuan = satuan;
    }
//    TEXTbayar

    public JTextField getTEXTbayar() {
        return TEXTbayar;
    }

    public void setTEXTbayar(JTextField TEXTbayar) {
        this.TEXTbayar = TEXTbayar;
    }
//    TEXTkembalian

    public JTextField getTEXTkembalian() {
        return TEXTkembalian;
    }

    public void setTEXTkembalian(JTextField TEXTkembalian) {
        this.TEXTkembalian = TEXTkembalian;
    }
}
